version: "3"
example-service:
    build: .
    container_name: golem # ?
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
#    command: npm start
